export const TEST = 'test';
export const RPC_V = '1.0';
export const DEFAULT_LOG_LEVEL = 'info';
export const DEBUG_LOG_LEVEL = 'trace';
export const SYNC_TIMEOUT = 10000;
export const DIFF = 2000;
export const RETRY_ATTEMPT = 100;
export const SYNC_INFO_RETRY_ATTEMPT = 50;
export const DATE_FORMAT = 'MMM D, hh:mm a';
export const PAYMENT_REQUEST_DETAIL_DATE_FORMAT = 'MMM D YYYY, hh:mm a';
export const UNPARSED_ADDRESS = 'Unparsed Address';
export const BLOCK_PAGE_SIZE = 10;
export const BLOCK_TXN_PAGE_SIZE = 10;
export const MASTERNODE_LIST_PAGE_SIZE = 10;
export const TOKEN_LIST_PAGE_SIZE = 10;
export const TOKEN_TRANSFERS_LIST_PAGE_SIZE = 10;
export const WALLET_TXN_PAGE_SIZE = 8;
export const MAX_WALLET_TXN_PAGE_SIZE = 200;
export const PAYMENT_REQ_PAGE_SIZE = 5;
export const PAYMENT_REQ_LIST_SIZE = 10;
export const QUEUE_CONCURRENCY = 5;
export const BALANCE_CRON_DELAY_TIME = 120000;
export const BITCOIN_CLI_REGEX = /bitcoin-cli/g;
export const DEFI_CLI_TEXT = 'defi-cli';
export const DEFAULT_ELECTRON_LOG_FORMAT =
  '[{y}-{m}-{d} {h}:{i}:{s}.{ms}] [IPC-RENDERER-{level}] {text}';
export const DEFAULT_ELECTRON_LOG_SIZE = 5; // IN MBs
export const BLOCKCHAIN_START_ERROR = 'Unable to start blockchain';
export const BLOCKCHAIN_START_SUCCESS = 'blockchain started successfully';
export const MAX_MONEY = 21000000;
export const DESTRUCTION_TX =
  '0000000000000000000000000000000000000000000000000000000000000000';
export const GET_NEW_ADDRESS_TYPE = 'legacy';
export const RESIGNED_STATE = 'RESIGNED';
export const CONFIRM_BUTTON_TIMEOUT = 1000;
export const CONFIRM_BUTTON_COUNTER = 5;
export const DAT_TOKEN = 'dat';
export const DCT_TOKEN = 'dct';
export const SWAP = 'swap';
export const POOL = 'pool';
export const DELETE = 'delete';
export const CREATE_DCT = 'dat';
export const MINIMUM_DFI_REQUIRED_FOR_TOKEN_CREATION = 101;
export const DCT_DISTRIBUTION = 'dct';
export const TOKEN_TRANSFERS = 'Transfers';
export const TOKEN_HOLDERS = 'Holders';
export const TOKEN_INFO = 'Info';
export const TOKEN_EXCHANGE = 'Exchange';
export const TOKEN_DEX = 'DEX';
export const TOKEN_READ_CONTRACT = 'Read Contract';
export const TOKEN_WRITE_CONTRACT = 'Write Contract';
export const TOKEN_ANALYSIS = 'Analysis';
export const TOKEN_COMMENTS = 'Comments';
export const UPDATE_MODAL_CLOSE_TIMEOUT = 1000;
export const ENTROPY_BITS = 256;
export const RANDOM_WORD_ENTROPY_BITS = 128;
export const DEFAULT_DFI_FOR_ACCOUNT_TO_ACCOUNT = 0.01;
export const UNDEFINED_STRING = 'undefined';
export const LIST_TOKEN_PAGE_SIZE = 500;
export const LIST_ACCOUNTS_PAGE_SIZE = 500;

export const MIN_WORD_INDEX = 1;
export const MAX_WORD_INDEX = 4;
export const TOTAL_WORD_LENGTH = 24;
export const RANDOM_WORD_LENGTH = 18;
export const IS_WALLET_CREATED_MAIN = 'isWalletCreatedMain';
export const IS_WALLET_CREATED_TEST = 'isWalletCreatedTest';
export const MAIN = 'main';
export const ADD = 'add';
export const REMOVE = 'remove';

export const POOL_PAIR_PAGE_SIZE = 500;
export const SHARE_POOL_PAGE_SIZE = 500;
export const WALLET_UNLOCK_TIMEOUT = 600; // time in seconds
export const IS_WALLET_LOCKED_MAIN = 'isWalletLockedMain';
export const IS_WALLET_LOCKED_TEST = 'isWalletLockedTest';
export const MASTERNODE_PARAMS_INCLUDE_FROM_START = true;
export const MASTERNODE_PARAMS_MASTERNODE_LIMIT = 1000;

export const LP_DAILY_DFI_REWARD = 'LP_DAILY_DFI_REWARD';
export const LP_SPLITS = 'LP_SPLITS';
export const VS_CURRENCY = 'usd';

export const DFI_SYMBOL = '0';
export const BTC_SYMBOL = '1';
export const ETH_SYMBOL = '2';
export const USDT_SYMBOL = '5';

export const COINGECKO_DFI_ID = 'defichain';
export const COINGECKO_BTC_ID = 'bitcoin';
export const COINGECKO_ETH_ID = 'ethereum';
export const COINGECKO_USDT_ID = 'tether';

export const STATS_API_BASE_URL = 'https://api.defichain.io/v1/stats';
export const COINGECKO_API_BASE_URL = 'https://api.coingecko.com/api/v3';
export const TELEGRAM_GERMAN_HELP_LINK = 'https://t.me/defiblockchain_DE';
export const TELEGRAM_ENGLISH_HELP_LINK = 'https://t.me/defiblockchain';
export const GITHUB_ISSUE_HELP_LINK =
  'https://github.com/DeFiCh/app/wiki/How-to-submit-issues-for-Defi-App';
export const DEFICHAIN_FAQ_HELP_LINK = 'https://defichain.com/learn/#faq';
export const DEFICHAIN_OFFICIAL_HELP_LINK = 'https://defichain.com/';
export const REDDIT_HELP_LINK = 'https://www.reddit.com/r/defiblockchain/';
