import { version, name } from '../../package.json';

export const PAYMENT_REQUEST = 'paymentRequests';
export const UNIT = 'unit';
export const BLOCK_STORAGE = 'blockStorage';
export const DATABASE_CACHE = 'databaseCache';
export const MAXIMUM_AMOUNT = 'maximumAmount';
export const MAXIMUM_COUNT = 'maximumCount';
export const FEE_RATE = 'feeRate';
export const DISPLAY_MODE = 'displayMode';
export const LANG_VARIABLE = 'lang';
export const LAUNCH_AT_LOGIN = 'launchAtLogin';
export const LAUNCH_MINIMIZED = 'minimizedAtLaunch';
export const PRUNE_BLOCK_STORAGE = 'pruneBlockStorage';
export const ENGLISH = 'en';
export const SCRIPT_VERIFICATION = 'scriptVerification';
export const GERMAN = 'de';
export const FRENCH = 'fr';
export const LIGHT_DISPLAY = 'LIGHT';
export const DARK_DISPLAY = 'DARK';
export const SAME_AS_SYSTEM_DISPLAY = 'SAME_AS_SYSTEM';
export const CONSOLE_PROMPT_LABEL = `${name}_v${version}`;
export const DEFI_CHAIN_HOMEPAGE = `https://www.defichain.io/`;
