name-template: 'v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'
categories:
  - title: '🚀 Features'
    labels:
      - 'kind/feature'
  - title: '🐛 Bug Fixes'
    labels:
      - 'kind/fix'
exclude-labels:
  - 'kind/chore'
  - 'kind/docs'
  - 'kind/refactor'
change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
change-title-escapes: '\<*_&'
version-resolver:
  minor:
    labels:
      - 'kind/feature'
  patch:
    labels:
      - 'kind/fix'
  default: patch
template: |
  ## What’s Changed

  $CHANGES
