name: OSS Governance

on:
  pull_request_target:
    branches: [main]
    types: [synchronize, opened, labeled, unlabeled]
  issues:
    types: [opened, labeled, unlabeled]
  issue_comment:
    types: [created]

permissions:
  contents: read
  issues: write
  pull-requests: write
  statuses: write
  checks: write

jobs:
  Bot:
    runs-on: ubuntu-latest
    steps:
      - uses: BirthdayResearch/oss-governance-bot@23a023a59e633947923a299f0497371576e12e78
