name: Sync labels

on:
  push:
    branches: [master]
    paths:
      # TODO(fuxingloh): delete/re-enable/migrate as it does not work well with version/* tags automation
      - .github/labels-disabled.yml

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@25a956c84d5dd820d28caab9f86b8d183aeeff3d

      - uses: micnncim/action-label-syncer@0e9c5104859d0e78219af63791636eba42382b5d
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
