name: Sync labels

on:
  push:
    branches: [main]
    paths:
      # TODO(fuxingloh): delete/re-enable/migrate as it does not work well with version/* tags automation
      - .github/labels-disabled.yml

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@ec3a7ce113134d7a93b817d10a8272cb61118579

      - uses: micnncim/action-label-syncer@3abd5ab72fda571e69fffd97bd4e0033dd5f495c
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
